config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations' }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root to: 'events#index'

  get 'events/:id/edit', to: 'events#edit', as: :edit_event
  patch 'events/:id', to: 'events#update'

  resources :event_attendings
  resources :users
  resources :events do
    post :add_attendee
    post :remove_attendee
    get :attended
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/event.rb
class Event < ApplicationRecord
  has_many :event_attendings, foreign_key: :attended_event_id
  has_many :attendees, through: :event_attendings, source: :event_attendee
  belongs_to :organiser, foreign_key: 'organiser_id', class_name: 'User'

  validates :name, :start_date, :description, presence: true
  validate :start_date_cannot_be_equal_to_end_date, :must_be_longer_than_30_minutes

  scope :upcoming, -> { where('start_date >= ?', DateTime.current) }
  scope :past_start_date, -> { where('start_date <= ?', DateTime.current) }
  scope :happening, -> { past_start_date.where('end_date >= ?', DateTime.current) }
  scope :past, -> { past_start_date.where('end_date <= ? OR end_date IS NULL', DateTime.current) }

  def display_date
    get_date(start_date, end_date)
  end

  private

  def get_date(start_date, end_date)
    if end_date.nil?
      return start_date.strftime('%B %d at %H:%M').to_s if this_year?(start_date)

      return start_date.strftime('%B %d %Y at %H:%M').to_s
    end
    return "#{start_date.strftime('%B %d, %H:%M')}-#{end_date.strftime('%H:%M')}" if same_day?(start_date, end_date)
    return "#{start_date.strftime('%b %d, %H:%M')} - #{end_date.strftime('%b %d, %H:%M')}" if same_month?(start_date,
                                                                                                          end_date)
    return "#{start_date.strftime('%b %d, %H:%M')} - #{end_date.strftime('%b %d, %H:%M')}" if this_year?(start_date)

    "#{start_date.strftime('%b %d %Y, %H:%M')} - #{end_date.strftime('%b %d %Y, %H:%M')}"
  end

  def same_year?(start_date, end_date)
    start_date.year == end_date.year
  end

  def this_year?(start_date)
    start_date.year == DateTime.now.year
  end

  def same_month?(start_date, end_date)
    return false unless same_year?(start_date, end_date)

    start_date.month == end_date.month
  end

  def same_day?(start_date, end_date)
    return false unless same_month?(start_date, end_date)

    start_date.day == end_date.day
  end

  def start_date_cannot_be_equal_to_end_date
    return if end_date.nil?

    errors.add(:end_date, 'cannot be same as start date') if start_date.end_of_minute == end_date.end_of_minute
  end

  def must_be_longer_than_30_minutes
    return if end_date.nil?

    if ((end_date.end_of_minute - start_date.end_of_minute) / 1.minutes) < 30
      errors.add(:end_date, 'must last longer than 30 minutes')
    end
  end
end

app/models/event_attending.rb
class EventAttending < ApplicationRecord
  belongs_to :event_attendee, class_name: 'User'
  belongs_to :attended_event, class_name: 'Event'
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :event_attendings, foreign_key: :event_attendee_id
  has_many :attended_events, through: :event_attendings
  has_many :organised_events, class_name: 'Event', dependent: :destroy

  ROLES = %w[attendee organiser]
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def active_filter_class(filter)
    if params[:filter] == filter
      'is-active'
    else
      ''
    end
  end
  helper_method :active_filter_class

  def select_events(base = Event.all)
    params[:filter] ||= 'all'
    @current_filter = params[:filter]
    @selected_events = base if @current_filter == 'all'
    @selected_events = base.happening if @current_filter == 'happening'
    @selected_events = base.upcoming if @current_filter == 'upcoming'
    @selected_events = base.past if @current_filter == 'past'
  end
end

app/controllers/eventattendings_controller.rb
class EventAttendings < ApplicationController
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_user!
  def index
    select_events
  end

  def new
    @event = Event.new
  end

  def create
    @event = Event.new(event_params)
    @event.organiser = current_user

    if @event.save
      redirect_to event_path(@event)
      @event.attendees << current_user
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
    event
    @attendees = event.attendees
  end

  def edit
    redirect_to event unless organiser? # TODO: Add flash
    event
  end

  def update
    event
    if event.update(event_params)
      redirect_to event
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    event
    event.destroy

    redirect_to root_path, status: :see_other
  end

  def add_attendee
    @event = Event.find(params[:event_id])
    @event.attendees << current_user

    redirect_to event_path(@event)
  end

  def remove_attendee
    @event = Event.find(params[:event_id])
    @event.attendees.delete(current_user)

    redirect_to event_path(@event)
  end

  def attended
    select_events(current_user.attended_events)
  end

  def attends?(user = current_user)
    event.attendees.exists?(user.id)
  end
  helper_method :attends?

  def organiser?(user = current_user)
    event.organiser == user
  end
  helper_method :organiser?

  private

  def event_params
    params.require(:event).permit(:name, :description, :start_date, :end_date, :organiser_id)
  end

  def event
    @event ||= Event.find(params[:id])
  end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  def create
    super
  end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def show
    user
    select_events(Event.where(organiser_id: user.id))
  end

  private

  def user
    @user ||= User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/_attend_buttons.html.erb
<% if organiser? %>
  <%= link_to "Edit event", edit_event_path(@event.id), class:"button is-medium is-primary" %>
  <%= link_to "Delete event", event_path(@event),
                      class: "button is-medium is-danger",
                      data: {
                        turbo: false,
                        controller: "confirmation",
                        action: "click->confirmation#toggleModal"
                      }
                      %>
<% elsif attends? %>
  <%= button_to "Do not attend", event_remove_attendee_path(@event), class: "button is-medium is-warning" %>
<% else %>
  <%= button_to "Attend", event_add_attendee_path(@event), class: "button is-medium is-success" %>
<% end %>

app/views/events/_confirmation_modal.html.erb
<div id="confirmation-modal" class="modal">
  <%= link_to '', event_path(@event), class: 'modal-background',
                    data: {
                      turbo: false,
                      controller: "confirmation",
                      action: "click->confirmation#toggleModal"
                    }
      %>
  <div class="modal-card">
    <header class="modal-card-head">
      <p class="modal-card-title">Are you sure you want to delete this event?</p>
      <%= link_to '', event_path(@event), class: 'delete',
                    data: {
                      turbo: false,
                      controller: "confirmation",
                      action: "click->confirmation#toggleModal"
                    }
      %>
    </header>
    <section class="modal-card-body">  
      <div class="field">
        <h3 class="title">
          <%= @event.name %>
        </h3>
      </div>

      <div class="field">
        <p class="is-size-5">
          <%= @event.description %>
        </p>
      </div>
    </section>
    <footer class="modal-card-foot">
      <div class="container">
        <div class="buttons is-grouped is-centered">
          <%= button_to "Destroy", event_path(@event),  
                          method: :delete,
                          class: "button is-danger is-medium" %>
          <%= link_to 'Cancel', event_path(@event), class: 'button is-medium',
                        data: {
                          turbo: false,
                          controller: "confirmation",
                          action: "click->confirmation#toggleModal"
                        } %>
        </div>
      </div>
    </footer>
  </div>
</div>

app/views/events/_list_events.html.erb
<% if params[:filter] == 'all' %>

  <div class="divider">CURRENTLY HAPPENING</div>  
  <div class="columns is-multiline is-centered">
    <%= render partial: 'events/listed_event', collection: @selected_events.happening %>
  </div>

  <div class="divider">UPCOMING</div>  
  <div class="columns is-multiline is-centered">
    <%= render partial: 'events/listed_event', collection: @selected_events.upcoming %>
  </div>

  <div class="divider">PAST</div>  
  <div class="columns is-multiline is-centered">
    <%= render partial: 'events/listed_event', collection: @selected_events.past %>
  </div>

<% else %>  
  <div class="columns is-multiline is-centered">
    <%= render partial: 'events/listed_event', collection: @selected_events.all %>
  </div>
<% end %>

app/views/events/_listed_event.html.erb
<div class="column is-narrow is-flex">
  <%= link_to event_url(listed_event.id), class: "box", style: "max-width:420px" do %>
    <h4 class="title is-4 mb-2">
      <%= listed_event.name %>
    </h4>
    <div class="has-text-weight-bold">
      <%= listed_event.display_date %>
    </div>
    <div>
      Organiser:
      <%= listed_event.organiser.name %>
    </div>
    <hr class="my-2">
    <p>
      <%= listed_event.description[0, 250] %>
    </p>
  <% end %>
</div>

app/views/events/attended.html.erb
<section class="is-medium is-centered m-4">
  <div class="field is-flex is-justify-content-center">
    <h1 class="title my-3">Attended events</h1>
  </div>
  <div class="field is-grouped-centered">
    <div class="buttons is-centered">
      <%= link_to 'All', event_attended_path(filter: "all"), class: "button is-rounded " + active_filter_class('all') %>
      <%= link_to 'Happening', event_attended_path(filter: "happening"), class: "button is-rounded " + active_filter_class('happening') %>
      <%= link_to 'Upcoming', event_attended_path(filter: "upcoming"), class: "button is-rounded " + active_filter_class('upcoming') %>
      <%= link_to 'Past', event_attended_path(filter: "past"), class: "button is-rounded " + active_filter_class('past') %>
    </div>
  </div>
  <%= render 'events/list_events' %>
</section>

app/views/events/edit.html.erb
<% content_for :head do %>
  <%= javascript_import_module_tag "calendar" %>
<% end %>

<section class="section is-normal">
    <div class="container">
      <div class="columns is-centered">
        <%= form_with model: @event do |f| %>
          <h1 class="title">Create an event</h1>
          <% if @event.errors.any? %>
            <div class="notification is-danger">
              <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being edited:</h2>
              <ul>
                <% @event.errors.each do |error| %>
                  <li><%= error.full_message %></li>
                <% end %>
              </ul>
            </div>
          <% end %>

          <%= f.label "Start and end date", class: "label" %>
          <div class="field">
            <input type="datetime">
          </div>

          <%= f.hidden_field :start_date, id: "start_date" %>
          <%= f.hidden_field :end_date, id: "end_date" %>

          <div class="field">
            <%= f.label :name, class: "label" %>
            <div class="control">
              <%= f.text_field :name, autofocus: true, class: "input is-medium" %>
            </div>
          </div>

          <div class="field">
            <%= f.label :description, class: "label" %>
            <%= f.text_area :description, class: "textarea is-medium " %>
          </div>

          <div class="field">
            <div class="control">
              <%= f.submit "Edit event", class: "button is-link" %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
</section>

app/views/events/index.html.erb
<%# TODO: add UPCOMING/PAST/CURRENT events %>
<section class="is-medium is-centered m-4">
  <div class="field is-grouped-centered">
    <div class="buttons is-centered">
      <%= link_to 'All', events_path(filter: "all"), class: "button is-rounded " + active_filter_class('all') %>
      <%= link_to 'Happening', events_path(filter: "happening"), class: "button is-rounded " + active_filter_class('happening') %>
      <%= link_to 'Upcoming', events_path(filter: "upcoming"), class: "button is-rounded " + active_filter_class('upcoming') %>
      <%= link_to 'Past', events_path(filter: "past"), class: "button is-rounded " + active_filter_class('past') %>
    </div>
  </div>
  <%= render 'events/list_events' %>
</section>

app/views/events/new.html.erb
<% content_for :head do %>
  <%= javascript_import_module_tag "calendar" %>
<% end %>

<section class="section is-normal">
    <div class="container">
      <div class="columns is-centered">
        <%= form_with model: @event do |f| %>
          <h1 class="title">Create an event</h1>

          <% if @event.errors.any? %>
            <div class="notification is-danger">
              <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being created:</h2>
              <ul>
                <% @event.errors.each do |error| %>
                  <li><%= error.full_message %></li>
                <% end %>
              </ul>
            </div>
          <% end %>

          <%= f.label "Start and end date", class: "label" %>
          <div class="field">
            <input type="datetime">
          </div>

          <%= f.hidden_field :start_date, id: "start_date" %>
          <%= f.hidden_field :end_date, id: "end_date" %>

          <div class="field">
            <%= f.label :name, class: "label" %>
            <div class="control">
              <%= f.text_field :name, autofocus: true, class: "input is-medium" %>
            </div>
          </div>

          <div class="field">
            <%= f.label :description, class: "label" %>
            <%= f.text_area :description, class: "textarea is-medium " %>
          </div>

          <div class="field">
            <div class="control">
              <%= f.submit "Create event", class: "button is-link" %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
</section>

app/views/events/show.html.erb
<section class="section is-medium">
  <div class="box container is-center">
    <%= render 'events/confirmation_modal' %>
    <div class="field">
      <h3 class="title">
        <%= @event.name %>
      </h3>
    </div>
    <div class="field">
      Organiser:
      <%= link_to @event.organiser.name, @event.organiser %>
    </div>
    <div class="field">
      <%= @event.display_date %>
    </div>
    <div class="field">
      <p class="is-size-5">
        <%= @event.description %>
      </p>
    </div>
    <div class="buttons is-centered">
      <%= render 'events/attend_buttons' %>
      <%= link_to "Back", :back, class: "button is-medium" %>
    </div>
  </div>
  <div class="box container is-center">
    <div class="field">
      <h4 class="subtitle">Attendees</h4>
    </div>
    <div class="field">
      <div class="buttons is-centered">
        <% @attendees.each do |attendee| %>
            <%= link_to attendee.name, attendee, class: "button is-normal is-link is-light"%>
        <% end %>
      </div>
    </div>
  </div>
</section>
<%# TODO: background = image according to title from some img db %>

app/views/layouts/_header.html.erb
<nav class="navbar is-transparent has-shadow">
  <div class="navbar-brand">
    <%= link_to root_path do %>
      <%= image_tag "logo.svg", width:64, alt: "Logo" %>
    <% end %>

    <div class="navbar-burger" data-target="navbarExampleTransparentExample">
      <span></span>
      <span></span>
      <span></span>
    </div>
  </div>

  <div class="navbar-menu">
    <div class="navbar-start">
      <div class="navbar-item has-dropdown is-hoverable">
        <%= link_to "Help", root_path, class: "navbar-link" %>
        <div class="navbar-dropdown is-boxed">
          <%= link_to "Navbar item", root_path, class: "navbar-item" %>
          <%= link_to "Navbar active item", root_path, class: "navbar-item is-active" %>
          <hr class="navbar-divider">
          <%= link_to "Navbar item", root_path, class: "navbar-item" %>
        </div>
      </div>
    </div>
    
    <div class="navbar-end">
      <% if user_signed_in? %>
        <div class="navbar-item">
          <div class="field is-grouped">
            <p class="control">
              <%= link_to "Create an event", new_event_path, class: "button is-primary"%>
            </p>
          </div>
        </div>

        <div class="navbar-menu">
          <div class="navbar-end">
            <div class="navbar-item has-dropdown is-hoverable ">
              <%= link_to current_user.name, user_url(current_user.id), class: "navbar-link" %>
              <div class="navbar-dropdown is-boxed is-right">
                <%= link_to "Attended events", event_attended_path(current_user), class: "navbar-item" %>
                <%= link_to "Navbar active item", root_path, class: "navbar-item is-active" %>
                <hr class="navbar-divider">
                <%= link_to "Log out", destroy_user_session_path, data: { turbo_method: :delete }, class: "navbar-item" %>
              </div>
            </div>
          </div>
        <% else %>
          <div class="navbar-item">
            <div class="field is-grouped">
              <p class="control">
                <%= link_to "Log in", new_user_session_path, class: "button"%>
              </p>
              <p class="control">
                <%= link_to "Sign up", new_user_registration_path, class: "button is-primary"%>
              </p>
            </div>
          </div>
      <% end %>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EventsApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload"  %>
    <%= javascript_importmap_tags %>
    <%= yield(:head) %>
  </head>

  <body>
    <%= render "layouts/header" %>
    <%= yield %>
  </body>
</html>

app/views/users/show.html.erb
<section class="section is-normal">
  <div class="container">
    <div class="columns is-centered">
      <div> 
        <div class="field is-flex is-justify-content-center">
          <h1 class="title my-3">  
            <%= @user.name %>'s events
          </h1>
        </div>
        <div class="field is-grouped-centered">
          <div class="buttons is-centered">
            <%= link_to 'All', events_path(filter: "all"), class: "button is-rounded " + active_filter_class('all') %>
            <%= link_to 'Happening', events_path(filter: "happening"), class: "button is-rounded " + active_filter_class('happening') %>
            <%= link_to 'Upcoming', events_path(filter: "upcoming"), class: "button is-rounded " + active_filter_class('upcoming') %>
            <%= link_to 'Past', events_path(filter: "past"), class: "button is-rounded " + active_filter_class('past') %>
          </div>
        </div>
        <%= render 'events/list_events' %>
      </div>
    </div>
  </div>
</section>